S -> P 
S -> S op_S P 

op_S -> space* "+"  
op_S -> space* "-"  # test

P -> T 
P -> P op_P T 

op_P -> space* "*"  
op_P -> space* "/"  

T -> space* "(" 
  # test
  S 
  space* 
  ")"  
T -> space* R 
T -> space* "-" T

R -> F      
R -> F "e" I 
        
F -> ["+"] F_pos
F -> "-" F_pos

F_pos -> N_l
F_pos -> N_l "." N_r          

N_l -> D            
N_l -> N_l D         

N_r -> 
N_r -> D N_r         

I -> ["+"] N_l  
I -> "-" N_l  

D -> "0"              
D -> "1"              
D -> "2"
D -> "3"              
D -> "4"              
D -> "5"              
D -> "6"              
D -> "7"              
D -> "8"              
D -> "9"              


space -> " "

