include $(HOME)/code/cpp/MakeRules
CPPFLAGS=$(OptCPPFLAGS) 
#CPPFLAGS=$(DebugCPPFLAGS)

CXX=g++
COMPILE.cpp= $(CXX) $(CPPFLAGS)  -c 
LIBS=



############################### Programs ################################

all:	\
  attr2_2pairs \
  attr2_multiply \
  attr2log \
  attrs \
  beta1_test \
  binomialCdf \
  char2attr \
  clust \
  count \
  dataset_test \
  distTriangle \
  dm2objs \
  dm2subset \
  linreg \
  linreg_test \
  logreg \
  logreg_test \
  matrix_test \
	mds \
	normalCdf \
	numeric_test \
	pairs2attr2 \
	pairs2Boolean \
	pca \
	pca2clusters \
	sim2dist \
  threshold \
	uniKernel \
	zipf_test
	

attr2_2pairs.o:  $(DM_HPP) 
attr2_2pairsOBJS=attr2_2pairs.o $(DM_OBJ) 
attr2_2pairs:	$(attr2_2pairsOBJS)
	$(CXX) -o $@ $(attr2_2pairsOBJS) $(LIBS)
	$(ECHO)

attr2_multiply.o:  $(DM_HPP) 
attr2_multiplyOBJS=attr2_multiply.o $(DM_OBJ) 
attr2_multiply:	$(attr2_multiplyOBJS)
	$(CXX) -o $@ $(attr2_multiplyOBJS) $(LIBS)
	$(ECHO)

attr2log.o:  $(DM_HPP) 
attr2logOBJS=attr2log.o $(DM_OBJ) 
attr2log:	$(attr2logOBJS)
	$(CXX) -o $@ $(attr2logOBJS) $(LIBS)
	$(ECHO)

attrs.o:  $(DM_HPP) 
attrsOBJS=attrs.o $(DM_OBJ) 
attrs:	$(attrsOBJS)
	$(CXX) -o $@ $(attrsOBJS) $(LIBS)
	$(ECHO)

beta1_test.o:  $(DM_HPP)
beta1_testOBJS=beta1_test.o $(DM_OBJ)
beta1_test:	$(beta1_testOBJS)
	$(CXX) -o $@ $(beta1_testOBJS) $(LIBS)
	$(ECHO)

binomialCdf.o:  $(DM_HPP)
binomialCdfOBJS=binomialCdf.o $(DM_OBJ)
binomialCdf:	$(binomialCdfOBJS)
	$(CXX) -o $@ $(binomialCdfOBJS) $(LIBS)
	$(ECHO)

char2attr.o:  $(DM_HPP) 
char2attrOBJS=char2attr.o $(DM_OBJ) 
char2attr:	$(char2attrOBJS)
	$(CXX) -o $@ $(char2attrOBJS) $(LIBS)
	$(ECHO)

clust.o:	$(DM_HPP) 
clustOBJS=clust.o $(DM_OBJ) 
clust:	$(clustOBJS)
	$(CXX) -o $@ $(clustOBJS) $(LIBS)
	$(ECHO)

count.o:	$(DM_DIR)/numeric.hpp $(COMMON_HPP)
countOBJS=count.o $(NUMERIC_OBJ) 
count:	$(countOBJS)
	$(CXX) -o $@ $(countOBJS) $(LIBS)
	$(ECHO)

dataset_test.o:  $(DM_HPP)
dataset_testOBJS=dataset_test.o $(DM_OBJ)
dataset_test:	$(dataset_testOBJS)
	$(CXX) -o $@ $(dataset_testOBJS) $(LIBS)
	$(ECHO)

distTriangle.o:  $(DM_HPP) 
distTriangleOBJS=distTriangle.o $(DM_OBJ) 
distTriangle:	$(distTriangleOBJS)
	$(CXX) -o $@ $(distTriangleOBJS) $(LIBS)
	$(ECHO)

dm2objs.o:  $(DM_HPP) 
dm2objsOBJS=dm2objs.o $(DM_OBJ) 
dm2objs:	$(dm2objsOBJS)
	$(CXX) -o $@ $(dm2objsOBJS) $(LIBS)
	$(ECHO)

dm2subset.o:  $(DM_HPP) 
dm2subsetOBJS=dm2subset.o $(DM_OBJ) 
dm2subset:	$(dm2subsetOBJS)
	$(CXX) -o $@ $(dm2subsetOBJS) $(LIBS)
	$(ECHO)

linreg.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
linregOBJS=linreg.o $(PREDICT_OBJ)
linreg:	$(linregOBJS)
	$(CXX) -o $@ $(linregOBJS) $(LIBS)
	$(ECHO)

linreg_test.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
linreg_testOBJS=linreg_test.o $(PREDICT_OBJ)
linreg_test:	$(linreg_testOBJS)
	$(CXX) -o $@ $(linreg_testOBJS) $(LIBS)
	$(ECHO)

logreg.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
logregOBJS=logreg.o $(PREDICT_OBJ)
logreg:	$(logregOBJS)
	$(CXX) -o $@ $(logregOBJS) $(LIBS)
	$(ECHO)

logreg_test.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
logreg_testOBJS=logreg_test.o $(PREDICT_OBJ)
logreg_test:	$(logreg_testOBJS)
	$(CXX) -o $@ $(logreg_testOBJS) $(LIBS)
	$(ECHO)

matrix_test.o:  $(COMMON_HPP) $(DM_DIR)/numeric.hpp $(DM_DIR)/matrix.hpp
matrix_testOBJS=matrix_test.o $(NUMERIC_OBJ) $(DM_DIR)/matrix.o
matrix_test:	$(matrix_testOBJS)
	$(CXX) -o $@ $(matrix_testOBJS) $(LIBS)  
	$(ECHO)

mds.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
mdsOBJS=mds.o $(DM_OBJ) $(DM_DIR)/prediction.o
mds:	$(mdsOBJS)
	$(CXX) -o $@ $(mdsOBJS) $(LIBS)
	$(ECHO)

normalCdf.o:  $(DM_HPP)
normalCdfOBJS=normalCdf.o $(DM_OBJ)
normalCdf:	$(normalCdfOBJS)
	$(CXX) -o $@ $(normalCdfOBJS) $(LIBS)
	$(ECHO)

numeric_test.o:  $(COMMON_HPP) $(DM_DIR)/numeric.hpp
numeric_testOBJS=numeric_test.o $(NUMERIC_OBJ)
numeric_test:	$(numeric_testOBJS)
	$(CXX) -o $@ $(numeric_testOBJS) $(LIBS)
	$(ECHO)

pairs2attr2.o:  $(DM_HPP) 
pairs2attr2OBJS=pairs2attr2.o $(DM_OBJ) 
pairs2attr2:	$(pairs2attr2OBJS)
	$(CXX) -o $@ $(pairs2attr2OBJS) $(LIBS)
	$(ECHO)

pairs2Boolean.o:  $(DM_HPP) 
pairs2BooleanOBJS=pairs2Boolean.o $(DM_OBJ) 
pairs2Boolean:	$(pairs2BooleanOBJS)
	$(CXX) -o $@ $(pairs2BooleanOBJS) $(LIBS)
	$(ECHO)

pca.o:  $(DM_HPP) $(DM_DIR)/prediction.hpp
pcaOBJS=pca.o $(DM_OBJ) $(DM_DIR)/prediction.o
pca:	$(pcaOBJS)
	$(CXX) -o $@ $(pcaOBJS) $(LIBS)
	$(ECHO)

pca2clusters.o:  $(COMMON_HPP) $(DM_DIR)/numeric.hpp
pca2clustersOBJS=pca2clusters.o $(NUMERIC_OBJ)
pca2clusters:	$(pca2clustersOBJS)
	$(CXX) -o $@ $(pca2clustersOBJS) $(LIBS)
	$(ECHO)

sim2dist.o:  $(DM_HPP) 
sim2distOBJS=sim2dist.o $(DM_OBJ) 
sim2dist:	$(sim2distOBJS)
	$(CXX) -o $@ $(sim2distOBJS) $(LIBS)
	$(ECHO)

threshold.o:  $(DM_HPP) 
thresholdOBJS=threshold.o $(DM_OBJ) 
threshold:	$(thresholdOBJS)
	$(CXX) -o $@ $(thresholdOBJS) $(LIBS)
	$(ECHO)

uniKernel.o:  $(DM_HPP) 
uniKernelOBJS=uniKernel.o $(DM_OBJ) 
uniKernel:	$(uniKernelOBJS)
	$(CXX) -o $@ $(uniKernelOBJS) $(LIBS)
	$(ECHO)

zipf_test.o:  $(DM_HPP) 
zipf_testOBJS=zipf_test.o $(DM_OBJ) 
zipf_test:	$(zipf_testOBJS)
	$(CXX) -o $@ $(zipf_testOBJS) $(LIBS)
	$(ECHO)

