include $(HOME)/code/cpp/MakeRules
CPPFLAGS=$(OptCPPFLAGS) 
#CPPFLAGS=$(DebugCPPFLAGS)

CXX=g++
COMPILE.cpp= $(CXX) $(CPPFLAGS)  -c 
LIBS=



############################### Programs ################################

all:	\
  attr2_2paup \
  attr2_2phylip \
  calibrateDissims \
  combine_dissims \
  compareTrees \
  distTree_new \
  feature2dissim \
  hash2dissim \
  hash_request2dissim \
  loci_request2dissim \
	makeDistTree \
	makeFeatureTree \
	mergeSimilarity \
	mlst2dissim \
	newick2tree \
	printDistTree \
  sampleReport \
  sim2dissim \
	tree2clusters \
	tree2dist
	

attr2_2paup.o:  $(DM_HPP) 
attr2_2paupOBJS=attr2_2paup.o $(DM_OBJ) 
attr2_2paup:	$(attr2_2paupOBJS)
	$(CXX) -o $@ $(attr2_2paupOBJS) $(LIBS)
	$(ECHO)

attr2_2phylip.o:  $(DM_HPP) 
attr2_2phylipOBJS=attr2_2phylip.o $(DM_OBJ) 
attr2_2phylip:	$(attr2_2phylipOBJS)
	$(CXX) -o $@ $(attr2_2phylipOBJS) $(LIBS)
	$(ECHO)

attr2_multiply.o:  $(DM_HPP) 
attr2_multiplyOBJS=attr2_multiply.o $(DM_OBJ) 
attr2_multiply:	$(attr2_multiplyOBJS)
	$(CXX) -o $@ $(attr2_multiplyOBJS) $(LIBS)
	$(ECHO)

calibrateDissims.o:  $(DM_HPP) $(PHYL_DIR)/evolution.hpp
calibrateDissimsOBJS=calibrateDissims.o $(DM_OBJ) $(PHYL_DIR)/evolution.o
calibrateDissims:	$(calibrateDissimsOBJS)
	$(CXX) -o $@ $(calibrateDissimsOBJS) $(LIBS)
	$(ECHO)

combine_dissims.o:  $(NUMERIC_HPP)
combine_dissimsOBJS=combine_dissims.o $(CPP_DIR)/common.o $(DM_DIR)/numeric.o
combine_dissims:	$(combine_dissimsOBJS)
	$(CXX) -o $@ $(combine_dissimsOBJS) $(LIBS)
	$(ECHO)

compareTrees.o:  $(COMMON_HPP) $(PHYL_DIR)/distTree.hpp $(PHYL_DIR)/featureTree.hpp
compareTreesOBJS=compareTrees.o $(DISTTREE_OBJ) $(PHYL_DIR)/featureTree.o
compareTrees:	$(compareTreesOBJS)
	$(CXX) -o $@ $(compareTreesOBJS) $(LIBS)
	$(ECHO)
	
distTree_new.o:  $(COMMON_HPP) $(PHYL_DIR)/distTree.hpp
distTree_newOBJS=distTree_new.o $(DISTTREE_OBJ)
distTree_new:	$(distTree_newOBJS)
	$(CXX) -o $@ $(distTree_newOBJS) $(LIBS)
	$(ECHO)

feature2dissim.o:  $(DM_HPP) 
feature2dissimOBJS=feature2dissim.o $(DM_OBJ) 
feature2dissim:	$(feature2dissimOBJS)
	$(CXX) -o $@ $(feature2dissimOBJS) $(LIBS)
	$(ECHO)

hash2dissim.o:  $(DM_HPP) $(PHYL_DIR)/evolution.hpp
hash2dissimOBJS=hash2dissim.o $(DM_OBJ) $(PHYL_DIR)/evolution.o
hash2dissim:	$(hash2dissimOBJS)
	$(CXX) -o $@ $(hash2dissimOBJS) $(LIBS)
	$(ECHO)

hash_request2dissim.o:  $(NUMERIC_HPP) $(PHYL_DIR)/evolution.hpp
hash_request2dissimOBJS=hash_request2dissim.o $(DM_OBJ) $(PHYL_DIR)/evolution.o
hash_request2dissim:	$(hash_request2dissimOBJS)
	$(CXX) -o $@ $(hash_request2dissimOBJS) $(LIBS)
	$(ECHO)

loci_request2dissim.o:  $(COMMON_HPP)  
loci_request2dissimOBJS=loci_request2dissim.o $(CPP_DIR)/common.o
loci_request2dissim:	$(loci_request2dissimOBJS)
	$(CXX) -o $@ $(loci_request2dissimOBJS) $(LIBS)
	$(ECHO)

makeDistTree.o:  $(COMMON_HPP) $(CPP_DIR)/graph.hpp $(DM_DIR)/dataset.hpp $(PHYL_DIR)/distTree.hpp
makeDistTreeOBJS=makeDistTree.o $(DISTTREE_OBJ)
makeDistTree:	$(makeDistTreeOBJS)
	$(CXX) -o $@ $(makeDistTreeOBJS) $(LIBS)
	$(ECHO)

makeFeatureTree.o:  $(NUMERIC_HPP) $(CPP_DIR)/graph.hpp $(PHYL_DIR)/featureTree.hpp 
makeFeatureTreeOBJS=makeFeatureTree.o $(FEATURE_TREE_OBJ)
makeFeatureTree:	$(makeFeatureTreeOBJS)
	$(CXX) -o $@ $(makeFeatureTreeOBJS) $(LIBS)
	$(ECHO)

mergeSimilarity.o:  $(DM_HPP) 
mergeSimilarityOBJS=mergeSimilarity.o $(DM_OBJ) 
mergeSimilarity:	$(mergeSimilarityOBJS)
	$(CXX) -o $@ $(mergeSimilarityOBJS) $(LIBS)
	$(ECHO)

mlst2dissim.o:  $(DM_HPP) 
mlst2dissimOBJS=mlst2dissim.o $(DM_OBJ) 
mlst2dissim:	$(mlst2dissimOBJS)
	$(CXX) -o $@ $(mlst2dissimOBJS) $(LIBS)
	$(ECHO)

newick2tree.o:  $(COMMON_HPP) $(PHYL_DIR)/distTree.hpp
newick2treeOBJS=newick2tree.o $(DISTTREE_OBJ)
newick2tree:	$(newick2treeOBJS)
	$(CXX) -o $@ $(newick2treeOBJS) $(LIBS)
	$(ECHO)

printDistTree.o:  $(COMMON_HPP) $(PHYL_DIR)/distTree.hpp
printDistTreeOBJS=printDistTree.o $(DISTTREE_OBJ)
printDistTree:	$(printDistTreeOBJS)
	$(CXX) -o $@ $(printDistTreeOBJS) $(LIBS)
	$(ECHO)

sampleReport.o:  $(COMMON_HPP)  
# $(PHYL_DIR)/distTree.hpp
sampleReportOBJS=sampleReport.o $(CPP_DIR)/common.o
# $(DISTTREE_OBJ)
sampleReport:	$(sampleReportOBJS)
	$(CXX) -o $@ $(sampleReportOBJS) $(LIBS)
	$(ECHO)

sim2dissim.o:  $(DM_HPP) $(PHYL_DIR)/evolution.hpp
sim2dissimOBJS=sim2dissim.o $(DM_OBJ) $(PHYL_DIR)/evolution.o
sim2dissim:	$(sim2dissimOBJS)
	$(CXX) -o $@ $(sim2dissimOBJS) $(LIBS)
	$(ECHO)

tree2clusters.o:  $(COMMON_HPP) $(PHYL_DIR)/distTree.hpp
tree2clustersOBJS=tree2clusters.o $(DISTTREE_OBJ)
tree2clusters:	$(tree2clustersOBJS)
	$(CXX) -o $@ $(tree2clustersOBJS) $(LIBS)
	$(ECHO)

tree2dist.o:  $(COMMON_HPP) $(DM_DIR)/dataset.hpp $(PHYL_DIR)/distTree.hpp
tree2distOBJS=tree2dist.o $(DISTTREE_OBJ)
tree2dist:	$(tree2distOBJS)
	$(CXX) -o $@ $(tree2distOBJS) $(LIBS)
	$(ECHO)

